# Directories:
PatternChrome_dir: ./
dataset_path: ./datasets
main_path: ./datasets/Binned_sequencing_data/
RNAseq_path: ./datasets/RNA_seq.RData
analysis_data: ./patternchrome/analysis_data/
Custom_functions: ./Custom_functions.R
Figures: ./patternchrome/Figures/

# Save the created plots?
Plot: FALSE

# Font size for ggplot2 figures
font_size: 18

# Number of cpu's to bee used for the paralleliztion (Carefull: some xgboost functions will use all availabe nevertheless...)
n_workers: 20
